version: "3.4"

services:
  api:
    image: cljubicbu/winter-academy-demo-backend:latest
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"

    environment:
      SA_PASSWORD: "WinterAcademyDemo123!"
      ACCEPT_EULA: "Y"